Fixes plone-pat-modal redirection issue after changing state from content menu
plone/plone.app.contentmenu pull request #70
Opened 2024-08-17 02:47 UTC by rohnsha0

fixes [#3989](https://github.com/plone/Products.CMFPlone/issues/3989)

2024-08-17 02:47 UTC, mister-roboto commented
@rohnsha0 thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-08-17 02:48 UTC, rohnsha0 commented
pre-commit.ci autofix

2024-08-17 02:48 UTC, rohnsha0 commented
@jenkins-plone-org please run jobs

2024-08-17 03:34 UTC, rohnsha0 commented
again same failure 

```
Setup failed:
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 124
Current browser version is 127.0.6533.99 with binary path /usr/bin/google-chrome
```

2024-08-19 06:47 UTC, petschki commented
@jenkins-plone-org please run jobs

2024-08-19 06:53 UTC, petschki requested changes
Just a typo in the changes. otherwise LGTM.

2024-08-19 06:53 UTC, petschki commented on news/3989.bugfix
> +Fixes plone-pat-modal redirection issue after changing state from content menu [rohnsha0]
```suggestion
Fixes pat-plone-modal redirection issue after changing state from content menu [rohnsha0]
```

2024-08-19 06:55 UTC, rohnsha0 commented
> Just a typo in the changes. otherwise LGTM.

done...

2024-08-19 06:56 UTC, petschki approved these changes
Merge when green.

2024-08-19 07:10 UTC, rohnsha0 commented
@jenkins-plone-org please run jobs

2024-08-19 07:58 UTC, merged